Lab3/Models/Book.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_3.Models
{
    public class Book
    {
        [HiddenInput]
        public int Id { get; set; }

        [Required(ErrorMessage = "Pole 'Tytuł' jest wymagane.")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Pole 'Autor' jest wymagane.")]
        public string Author { get; set; }

        [Required(ErrorMessage = "Pole 'Liczba stron' jest wymagane.")]
        [Range(1, int.MaxValue, ErrorMessage = "Liczba stron musi być większa niż 0.")]
        public int PageCount { get; set; }

        [Required(ErrorMessage = "Pole 'ISBN' jest wymagane.")]
        public string ISBN { get; set; }

        [Required(ErrorMessage = "Pole 'Rok wydania' jest wymagane.")]
        [Range(1000, 9999, ErrorMessage = "Podaj poprawny rok wydania.")]
        public int YearPublished { get; set; }

        [Required(ErrorMessage = "Pole 'Wydawnictwo' jest wymagane.")]
        public string Publisher { get; set; }
    }

}

Lab3/Models/Contact.cs
using Microsoft.AspNetCore.Mvc;
using System.ComponentModel.DataAnnotations;

namespace Laboratorium_3.Models
{
    public class Contact
    {
        [HiddenInput]
        public int Id { get; set; }
        [Required(ErrorMessage = "Musisz podać imię!")]
        [StringLength(maximumLength:50, ErrorMessage = "Zbyt długie imię, podaj mniej niż 50 znaków")]
        public string Name { get; set; }
        [EmailAddress]
        public string Email { get; set; }
        [Phone]
        public string Phone { get; set; }
        public DateTime? Birth { get; set; }
    }
}

Lab3/Models/ErrorViewModel.cs
namespace Laboratorium_3.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab3/Controllers/BookController.cs
using Laboratorium_3.Models;
using Microsoft.AspNetCore.Mvc;

namespace Laboratorium_3.Controllers
{
    public class BookController : Controller
    {
        private static Dictionary<int, Book> _books = new Dictionary<int, Book>();

        [HttpGet]
        public IActionResult Index()
        {
            var books = _books.Values.ToList();
            return View(books);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Book model)
        {
            if (ModelState.IsValid)
            {
                int id = _books.Keys.Count != 0 ? _books.Keys.Max() + 1 : 1;
                model.Id = id;
                _books.Add(id, model);

                return RedirectToAction("Index");
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            if (_books.ContainsKey(id))
            {
                var book = _books[id];
                return View(book);
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult Edit(Book model)
        {
            if (ModelState.IsValid)
            {
                if (_books.ContainsKey(model.Id))
                {
                    _books[model.Id] = model;
                    return RedirectToAction("Index");
                }
            }

            return View(model);
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (_books.ContainsKey(id))
            {
                var book = _books[id];
                return View(book);
            }

            return NotFound();
        }

        [HttpGet]
        public IActionResult Delete(int id)
        {
            if (_books.ContainsKey(id))
            {
                var book = _books[id];
                return View(book);
            }

            return NotFound();
        }

        [HttpPost]
        public IActionResult Delete(Book book)
        {
            _books.Remove(book.Id);
            return RedirectToAction("Index");
        }
    }

}

Lab3/Controllers/ContactController.cs
using Microsoft.AspNetCore.Mvc;
using Laboratorium_3.Models;
using System.Reflection;

namespace Laboratorium_3.Controllers
{
    public class ContactController : Controller
    {
        static readonly Dictionary<int, Contact> _contacts = new Dictionary<int, Contact>();
        static int _id = 1;
        public IActionResult Index()
        {
            return View(_contacts);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Contact model)
        {
           if (ModelState.IsValid)
           {
               model.Id = _id++;
                _contacts[model.Id] = model;
               return RedirectToAction("Index");
           }
           return View();
        }

        [HttpGet]
        public IActionResult Update(int id)
        {
            return View(_contacts[id]);
        }

        [HttpPost]
        public IActionResult Update(Contact model)
        {
            if (ModelState.IsValid)
            {
                _contacts[model.Id] = model;
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult Details(int id)
        {
            if (_contacts.ContainsKey(id))
            {
                var contact = _contacts[id];
                return View(contact);
            }

            return NotFound();
        }
        
        [HttpGet]
        public IActionResult Delete(int id)
        {
            return View(_contacts[id]);
        }

        [HttpPost]
        public IActionResult Delete(Contact model)
        {
            _contacts.Remove(model.Id);
            return RedirectToAction("Index");
        }
    }
}
 

Lab3/Controllers/HomeController.cs
using Laboratorium_3.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Laboratorium_3.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab3/Views/Book/Create.cshtml
@model Book

<h2>Dodaj nową książkę</h2>

<form asp-action="Create" asp-controller="Book" method="post">
    <div asp-validation-summary="All" class="text-danger"></div>

    <div class="form-group">
        <label asp-for="Title">Tytuł</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author">Autor</label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PageCount">Liczba stron</label>
        <input asp-for="PageCount" class="form-control" />
        <span asp-validation-for="PageCount" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ISBN">ISBN</label>
        <input asp-for="ISBN" class="form-control" />
        <span asp-validation-for="ISBN" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="YearPublished">Rok wydania</label>
        <input asp-for="YearPublished" class="form-control" />
        <span asp-validation-for="YearPublished" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Publisher">Wydawnictwo</label>
        <input asp-for="Publisher" class="form-control" />
        <span asp-validation-for="Publisher" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Dodaj</button>
</form>

Lab3/Views/Book/Delete.cshtml
@model Book

<h2>Usuń książkę</h2>

<div>
    <h4>Czy na pewno chcesz usunąć tę książkę?</h4>
    <h4>Tytuł: @Model.Title</h4>
    <h4>Autor: @Model.Author</h4>
    <h4>Liczba stron: @Model.PageCount</h4>
    <h4>ISBN: @Model.ISBN</h4>
    <h4>Rok wydania: @Model.YearPublished</h4>
    <h4>Wydawnictwo: @Model.Publisher</h4>
</div>

<form asp-action="Delete" asp-controller="Book" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <input type="submit" value="Usuń" class="btn btn-danger" />
        <a asp-action="Index" asp-controller="Book" class="btn btn-secondary">Anuluj</a>
    </div>
</form>

Lab3/Views/Book/Details.cshtml
@model Book

<h2>Szczegóły ksiązki</h2>

<div>
    <p>Tytuł: @Model.Title</p>
    <p>Autor: @Model.Author</p>
    <p>Liczba stron: @Model.PageCount</p>
    <p>ISBN: @Model.ISBN</p>
    <p>Rok wydania: @Model.YearPublished</p>
    <p>Wydawnictwo: @Model.Publisher</p>
</div>

<a asp-action="Index" asp-controller="Book" class="btn btn-secondary">Wróć</a>

Lab3/Views/Book/Edit.cshtml
@model Book

<h2>Edytuj książkę</h2>

<form asp-action="Edit" asp-controller="Book" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Title">Tytuł</label>
        <input asp-for="Title" class="form-control" />
        <span asp-validation-for="Title" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Author">Autor</label>
        <input asp-for="Author" class="form-control" />
        <span asp-validation-for="Author" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PageCount">Liczba stron</label>
        <input asp-for="PageCount" class="form-control" />
        <span asp-validation-for="PageCount" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="ISBN">ISBN</label>
        <input asp-for="ISBN" class="form-control" />
        <span asp-validation-for="ISBN" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="YearPublished">Rok wydania</label>
        <input asp-for="YearPublished" class="form-control" />
        <span asp-validation-for="YearPublished" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Publisher">Wydawnictwo</label>
        <input asp-for="Publisher" class="form-control" />
        <span asp-validation-for="Publisher" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Zapisz</button>
</form>

Lab3/Views/Book/Index.cshtml
@model List<Book>

<h1>Lista książek</h1>
<a class="btn btn-primary" asp-controller="Book" asp-action="Create">Dodaj książkę</a>

<table class="table">
    <thead>
        <tr>
            <th>Tytuł</th>
            <th>Autor</th>
            <th>Liczba stron</th>
            <th>ISBN</th>
            <th>Rok wydania</th>
            <th>Wydawnictwo</th>
            <th>Akcje</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var book in Model)
        {
            <tr>
                <td>@book.Title</td>
                <td>@book.Author</td>
                <td>@book.PageCount</td>
                <td>@book.ISBN</td>
                <td>@book.YearPublished</td>
                <td>@book.Publisher</td>
                <td>
                    <a class="btn btn-outline-primary" asp-controller="Book" asp-action="Edit" asp-route-id="@book.Id">Edytuj</a>
                    <a class="btn btn-outline-info" asp-controller="Book" asp-action="Details" asp-route-id="@book.Id">Szczegóły</a>
                    <a class="btn btn-outline-danger" asp-controller="Book" asp-action="Delete" asp-route-id="@book.Id">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lab3/Views/Contact/Create.cshtml
@model Contact

<h1>Dodaj kontakt</h1>
<form asp-controller="Contact" asp-action="Create" method="post">
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name" />
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Phone">Numer telefonu</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>

    </div>

    <div class="mb-3">
        <label asp-for="Birth">Data urodzenia</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn-primary">Utwórz</button>
    </div>
</form>

Lab3/Views/Contact/Delete.cshtml
@model Contact
@{
    ViewData["Title"] = "Usuń kontakt";
}

<h2>Czy na pewno chcesz usunąć ten kontakt?</h2>
<div>
    <h4>Imię: @Model.Name</h4>
    <h4>Email: @Model.Email</h4>
    <h4>Numer telefonu: @Model.Phone</h4>
    <h4>Data urodzenia: @Model.Birth</h4>
</div>

<form asp-action="Delete" asp-controller="Contact" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Usuń</button>
    <a asp-action="Index" asp-controller="Contact" class="btn btn-secondary">Anuluj</a>
</form>

Lab3/Views/Contact/Details.cshtml
@model Contact

<h1>Szczegóły kontaktu</h1>

<div>
    <p>Imię: @Model.Name</p>
    <p>Email: @Model.Email</p>
    <p>Numer telefonu: @Model.Phone</p>
    <p>Data urodzenia: @Model.Birth</p>
</div>

<a asp-action="Index" asp-controller="Contact" class="btn btn-secondary">Wróć</a>

Lab3/Views/Contact/Index.cshtml
@model Dictionary<int, Contact>

<h1>
    Lista kontaktów
</h1>
<a class="btn btn-primary" asp-controller="Contact" asp-action="Create">
    Utwórz kontakt
</a>

<table class="table">
    <thead>
    <tr>
        <th>Imię</th>
        <th>Email</th>
        <th>Akcje</th>
    </tr>
    </thead>
    <tbody>
        @foreach(var item in @Model)
        {
            <tr>
                <td>
                    @item.Value.Name
                </td>
                <td>
                    @item.Value.Email
                </td>
                <td>
                    <a class="btn btn-outline-primary" asp-controller="Contact" asp-action="Update" asp-route-id="@item.Key">Edytuj</a>
                    <a class="btn btn-outline-info" asp-controller="Contact" asp-action="Details" asp-route-id="@item.Key">Szczegóły</a>
                    <a class="btn btn-outline-danger" asp-controller="Contact" asp-action="Delete" asp-route-id="@item.Key">Usuń</a>
                </td>
            </tr>
        }
    </tbody>
</table>

Lab3/Views/Contact/Update.cshtml
@model Contact

<h1>Edytuj kontakt</h1>
<form asp-controller="Contact" asp-action="Update" method="post">
    <input asp-for="Id" />
    <div class="mb-3">
        <label asp-for="Name">Imię</label>
        <input class="form-control" asp-for="Name"/>
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Email">Email</label>
        <input class="form-control" asp-for="Email" />
        <span class="text-danger" asp-validation-for="Email"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Phone">Numer telefonu</label>
        <input class="form-control" asp-for="Phone" />
        <span class="text-danger" asp-validation-for="Phone"></span>

    </div>

    <div class="mb-3">
        <label asp-for="Birth">Data urodzenia</label>
        <input class="form-control" asp-for="Birth" />
        <span class="text-danger" asp-validation-for="Birth"></span>
    </div>
    <div class="mb-3">
        <button type="submit" class="btn-primary">Zapisz</button>
    </div>
</form>

Lab3/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Laboratorium_3</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Laboratorium_3.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Laboratorium_3</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Book" asp-action="Index">Book</a>
                        </li>

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Laboratorium_3 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>